version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      avalonia:
        patterns:
          - "Avalonia*"
      winui:
        patterns:
          - "Microsoft.WindowsAppSDK*"
      other:
        patterns:
          - "*"
